name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-checks:
    name: Format, Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::874456855495:role/github-actions-terraform-plan
          aws-region: eu-west-2

      - name: Terraform format check
        run: terraform fmt -check -recursive ../..

      - name: Terraform initialise
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Show Terraform working directory
        working-directory: terraform/environments/dev
        run: |
                 pwd
                    find . -maxdepth 2 -type f -name "*.tf" -print
                    terraform workspace show

      - name: Terraform plan
        run: terraform plan -no-color