name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  contents: read

jobs:
  terraform-checks:
    name: Format and Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.5"

      - name: Terraform format check
        run: terraform fmt -check -recursive ../..

      - name: Terraform initialise without backend
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate